spring:
  redis:
    database: 0
    host: 139.155.38.243
    port: 12379
    password: 112345
    timeout: 5000
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: -1
        min-idle: 0
